import os
import sys
from subprocess import call
import json
import shutil

jar_files = []
with os.scandir() as iterator:
	for file in iterator:
		if file.name.endswith(".jar") and file.is_file():
			jar_files.append(file);

if len(jar_files) == 0:
	print("No jar files found")
	sys.exit(1)

print("Which jar file do you want to extract the data from?\n")
for i in range(len(jar_files)):
	print("\t[" + str(i) + "] " + jar_files[i].name)

file_num = input("\nEnter file number: ")
try:
	input_num = int(file_num)
	is_int = True
except:
	is_int = False

while not is_int or ( input_num < 0 or input_num >= len(jar_files)):
	print("There is no file numbered '" + str(file_num) +"'")
	file_num = input("\nEnter file number: ")
	try:
		input_num = int(file_num)
		is_int = True
	except:
		is_int = False



jar_file = jar_files[input_num].name
command = ["java", "-cp", jar_file, "net.minecraft.data.Main", "--reports"]
run_code = call(command)
if run_code != 0:
	print("Error extracting contents")
	sys.exit(1)

blocks_json = open("generated\\reports\\blocks.json", "r")
blocks = json.load(blocks_json)
blocks_json.close()
new_blocks = {}

for block in blocks.keys():
	blocks[block].pop("states", None)
	if not "properties" in blocks[block]:
		blocks[block]["properties"] = {}
	if block.startswith("minecraft:"):
		new_block = block[10:]
	else:
		new_block = block
	new_blocks[new_block] = blocks[block]


blocks_py_name = "Blocks.py"
try:
	os.remove(blocks_py_name)
except:
	None

blocks_py = open(blocks_py_name, "w")
blocks_py.write("# File automatically generated by UpdateAll.py\n")
blocks_py.write("BLOCKS = " + str(new_blocks))
blocks_py.close()

commands_json = open("generated\\reports\\commands.json", "r")
commands = json.load(commands_json)
commands_json.close()

commands["children"]["execute"]["children"]["run"]["redirect"] = ["root"]

commands_py_name = "CommandTree.py"
try:
	os.remove(commands_py_name)
except:
	None

commands_py = open(commands_py_name, "w")
commands_py.write("# File automatically generated by UpdateAll.py\n")
commands_py.write("COMMAND_TREE = " + str(commands))
commands_py.close()

items_json = open("generated\\reports\\items.json", "r")
items = list(json.load(items_json).keys())
items_json.close()

for i in range(len(items)):
	item = items[i]
	if item.startswith("minecraft:"):
		item = item[10:]
		items[i] = item

items_py_name = "Items.py"
try:
	os.remove(items_py_name)
except:
	None

items_py = open(items_py_name, "w")
items_py.write("# File automatically generated by UpdateAll.py\n")
items_py.write("ITEMS = " + str(set(items)))
items_py.close()

shutil.rmtree("generated")
shutil.rmtree("logs")

#java -cp minecraft_server.%version%.jar net.minecraft.data.Main --all
